name = "SrgTools"
uuid = "a5ac757b-1a8a-4171-b42e-860ab9964fde"
authors = ["Julius Krebbekx <krebbekx.julius@gmail.com>"]
version = "0.1.0"

[deps]
ControlSystemsBase = "aaaaaaaa-a6ca-5380-bf3e-84a91bcd477e"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
ControlSystemsBase = "1.15.1"
LaTeXStrings = "1.4.0"
LinearAlgebra = "1.11.0"
Plots = "1.40.13"
Test = "1.11.0"
